version: v1

labels:
  - label: 'enhancement'
    sync: true
    matcher:
      title: '^feat(\([\w/]+\))?: .*'

  - label: 'bug'
    sync: true
    matcher:
      title: '^fix(\((?!deps)[\w/]+\))?: .*'

  - label: 'refactor'
    sync: true
    matcher:
      title: '^(refactor|perf)(\([\w/]+\))?: .*'

  - label: 'documentation'
    sync: true
    matcher:
      title: '^docs(\([\w/]+\))?: .*'

  - label: 'test'
    sync: true
    matcher:
      title: '^test(\([\w/]+\))?: .*'

  - label: 'build'
    sync: true
    matcher:
      title: '^(ci|build)(\([\w/]+\))?: .*'

  - label: 'chore'
    sync: true
    matcher:
      title: '^chore(\((?!deps)[\w/]+\))?: (?!release ).*'

  - label: 'dependency'
    sync: true
    matcher:
      branch: '^renovate/.*'

checks:
  - context: 'Semantic Pull Request'
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for merge.
    labels:
      any:
        - enhancement
        - bug
        - refactor
        - documentation
        - test
        - build
        - chore
        - dependency
      