name: RETIRED - Prepare for release
on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: Release version to use
        required: true
      snapshot_version:
        type: string
        description: Next snapshot version to use
        required: true
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure for GitHub
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
          server-id: github
          server-username: ${{ secrets.GITHUB_USERNAME }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git user
        run: |
          git config user.email "adam.setch@outlook.com"
          git config user.name "Adam Setch"
      - name: Prepare new release
        run: mvn --batch-mode release:prepare -Darguments=-DreleaseVersion=${{ github.event.inputs.release_version }} -Darguments=-DdevelopmentVersion=${{ github.event.inputs.release_version }}
